const Data = [
    {
        id:1,
        name:"RepairHeaven",
        stack:["HTML","CSS","JS","REACTJS"],
        image:"images2/RepairHeaven.png",
        website:"https://venkatesh-na.github.io/RepairHeaven/",
        githubrepo:"https://github.com/venkatesh-na/RepairHeaven",
        description:""
      
    },
    {
        id:2,
        name:"ShopCart",
        stack:["HTML","CSS","JS","REACTJS"],
        image:"images2/ShopCart.png",
        website:"https://venkatesh-na.github.io/ShopCart/",
        githubrepo:"https://github.com/venkatesh-na/ShopCart",
         
    },
    {
        id:3,
        name:"MovieSearch",
        stack:["HTML","CSS","JS","REACTJS"],
        image:"images2/MovieSearch.png",
        website:"https://venkatesh-na.github.io/MovieSearch/",
        githubrepo:"https://github.com/venkatesh-na/MovieSearch"
    },
    {
        id:4,
        name:"Doorstep-Chai",
        stack:["HTML","CSS","JS","REACTJS","FIREBASE"],
        image:"images2/Doorstep-Chai.png",
        website:"https://venkatesh-na.github.io/DoorStep-Chai/",
        githubrepo:"https://github.com/venkatesh-na/DoorStep-Chai"
        
    },
    {
        id:5,
        name:"Priority-Todo",
        stack:["HTML","CSS","JS","REACTJS"],
        image:"images2/Priority-Todo.png",
        website:"https://venkatesh-na.github.io/Priority-Todo/",
        githubrepo:"https://github.com/venkatesh-na/Priority-Todo"
    },
    {
        id:6,
        name:"WeatherApp",
        stack:["HTML","CSS","JS","REACTJS"],
        image:"images2/weather.png",
        website:"https://venkatesh-na.github.io/WeatherApp/",
        githubrepo:"https://github.com/venkatesh-na/WeatherApp"
    },
    {
        id:7,
        name:"BreakingBad",
        stack:["HTML","CSS","JS"],
        image:"images2/BreakingBad.png",
        website:"https://venkatesh-na.github.io/BreakingBadCharacters/",
        githubrepo:"https://github.com/venkatesh-na/BreakingBadCharacters"
    }
]
export default Data;